### ISSUE TITLE
Intranet deployment

### ISSUE THREAD

**Issue by christian-2** [edumeet/edumeet-ansible#4]
The current Ansible playbook assumes that it can launch a fully Internet-accessible, interim server on the host in order to obtain a verified certificate from Let's Encrypt. This does not work well for intranet deployments.

The following constitutes a preliminary (if rough) workaround. A clear, configurable option would be desirable.

    vim playbook.yml # 1.
    vim roles/mm/tasks/mm.yml # 2.
    ls -l certs # 3.
    ansible-playbook -i hosts -u ansible playbook.yml -K

1. in `role: geerlingguy.certbot`, change to `certbot_create_if_missing: false`
2. in `name: Copy certs`, change to `src: "certs/{{ item.src }}`, `remote_src: no`
3. place appropriate`{fullchain,privkey}.pem` (not necessarily from Let's Enrcrpt; with correct file modes) in here

**Comment by misi** [comment]
Please send  a Pull Request if ansible playbook finds cert and privkey in the host vars or group vars then not request a new cert but use this provided cert file.

**Comment by misi** [comment]
And we also don't need to renew and renew logic should not be installed..

**Comment by misi** [comment]
Please test it.
