### ISSUE TITLE
Configuration file templates assume master

### ISSUE THREAD

**Issue by christian-2** [edumeet/edumeet-ansible#5]
By setting `mm_branch`/`mm_tag` e.g. either to `master`/`latest` or to `dev`/`dev` one  can choose a particular version of `multiparty-meeting` for installation. However, the configuration file templates apparently assume the master version. 

For instance, `roles/mm/templates/server-config.j2` does not set `BYPASS_ROOM_LOCK`, which is not tolerated by the current `dev` version. Settings also differ between versions, e.g. `master` supports `turnServers` whereas `dev` supports `turnAPIKey`, `turnAPIURI`, `turnAPIparams`, and `backupTurnServers`.

The playbook should perhaps apply different templates for different versions (e.g. `roles/mm/templates/{dev,master}/server-config.j2`).

**Comment by misi** [comment]
True.. I need to check it. @christian-2  thx..

**Comment by misi** [comment]
@christian-2  please check it and let me know if any adjustment needed.

**Comment by christian-2** [comment]
@misi looks good; also better to support fixed version numbers than branch names as in my example; haven't tried a fresh install based on it, though

**Comment by misi** [comment]
Thanks for the feedback
